Listen 18080

<VirtualHost *:18080>
    ServerName localhost
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride None
        Require all granted
        Options -Indexes +FollowSymLinks

        RewriteEngine On

        RewriteRule ^(api|webhooks)(/.*)?$ index.php [QSA,L]

        RewriteCond %{REQUEST_FILENAME} -f
        RewriteRule ^ - [L]
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
